FROM quay.io/buildah/stable

RUN dnf install -y jq && \
    dnf install -y git && \
    dnf install -y curl && \
    dnf install -y podman && \
    dnf install -y skopeo && \
    dnf install -y aspnetcore-runtime-8.0 && \
    dnf install -y fuse-overlayfs

RUN  mkdir /azp 

WORKDIR /azp

COPY ./resources/start.sh ./

RUN chmod +x ./start.sh

ENV AGENT_ALLOW_RUNASROOT="true"
ENV TARGETARCH="linux-x64"
ENV BUILDAH_ISOLATION="chroot"

ENTRYPOINT ./start.sh

